// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package euserv

const (

	// ErrCodeModifyServiceException for service response error code
	// "ModifyServiceType".
	ErrCodeModifyServiceException = "ModifyServiceType"

	// ErrCodeServiceFailureException for service response error code
	// "ServiceFailure".
	ErrCodeServiceFailureException = "ServiceFailure"
)
