// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package euserv provides the client and types for making API
// requests to Eucalyptus Services.
//
// See https://docs.aws.amazon.com/goto/WebAPI/euserv-2010-01-01 for more information on this service.
//
// See euserv package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/euserv/
//
// Using the Client
//
// To use Eucalyptus Services with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the Eucalyptus Services client for more information on
// creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/euserv/#New
package euserv
