// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package euserv

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sjones4/eucalyptus-sdk-go/internal/awsutil"
)

type DescribeAvailableServiceTypesInput struct {
	_ struct{} `type:"structure"`

	Verbose *bool `locationName:"Verbose" type:"boolean"`
}

// String returns the string representation
func (s DescribeAvailableServiceTypesInput) String() string {
	return awsutil.Prettify(s)
}

type DescribeAvailableServiceTypesOutput struct {
	_ struct{} `locationName:"DescribeAvailableServiceTypesResponseType" type:"structure"`

	Available []ServiceType `locationName:"available" locationNameList:"item" type:"list"`
}

// String returns the string representation
func (s DescribeAvailableServiceTypesOutput) String() string {
	return awsutil.Prettify(s)
}

const opDescribeAvailableServiceTypes = "DescribeAvailableServiceTypes"

// DescribeAvailableServiceTypesRequest returns a request value for making API operation for
// Eucalyptus Cloud Service Management Service.
//
//    // Example sending a request using DescribeAvailableServiceTypesRequest.
//    req := client.DescribeAvailableServiceTypesRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/euserv-2010-01-01/DescribeAvailableServiceTypes
func (c *Client) DescribeAvailableServiceTypesRequest(input *DescribeAvailableServiceTypesInput) DescribeAvailableServiceTypesRequest {
	op := &aws.Operation{
		Name:       opDescribeAvailableServiceTypes,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DescribeAvailableServiceTypesInput{}
	}

	req := c.newRequest(op, input, &DescribeAvailableServiceTypesOutput{})
	return DescribeAvailableServiceTypesRequest{Request: req, Input: input, Copy: c.DescribeAvailableServiceTypesRequest}
}

// DescribeAvailableServiceTypesRequest is the request type for the
// DescribeAvailableServiceTypes API operation.
type DescribeAvailableServiceTypesRequest struct {
	*aws.Request
	Input *DescribeAvailableServiceTypesInput
	Copy  func(*DescribeAvailableServiceTypesInput) DescribeAvailableServiceTypesRequest
}

// Send marshals and sends the DescribeAvailableServiceTypes API request.
func (r DescribeAvailableServiceTypesRequest) Send(ctx context.Context) (*DescribeAvailableServiceTypesResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DescribeAvailableServiceTypesResponse{
		DescribeAvailableServiceTypesOutput: r.Request.Data.(*DescribeAvailableServiceTypesOutput),
		response:                            &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DescribeAvailableServiceTypesResponse is the response type for the
// DescribeAvailableServiceTypes API operation.
type DescribeAvailableServiceTypesResponse struct {
	*DescribeAvailableServiceTypesOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DescribeAvailableServiceTypes request.
func (r *DescribeAvailableServiceTypesResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
