// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package euprop

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sjones4/eucalyptus-sdk-go/internal/awsutil"
)

type ModifyPropertyInput struct {
	_ struct{} `type:"structure"`

	// Name is a required field
	Name *string `locationName:"Name" type:"string" required:"true"`

	Reset *bool `locationName:"Reset" type:"boolean"`

	Value *string `locationName:"Value" type:"string"`
}

// String returns the string representation
func (s ModifyPropertyInput) String() string {
	return awsutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *ModifyPropertyInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "ModifyPropertyInput"}

	if s.Name == nil {
		invalidParams.Add(aws.NewErrParamRequired("Name"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type ModifyPropertyOutput struct {
	_ struct{} `locationName:"ModifyPropertyValueResponseType" type:"structure"`

	Name *string `locationName:"name" type:"string"`

	OldValue *string `locationName:"oldValue" type:"string"`

	Value *string `locationName:"value" type:"string"`
}

// String returns the string representation
func (s ModifyPropertyOutput) String() string {
	return awsutil.Prettify(s)
}

const opModifyProperty = "ModifyProperty"

// ModifyPropertyRequest returns a request value for making API operation for
// Eucalyptus Cloud Properties Service.
//
//    // Example sending a request using ModifyPropertyRequest.
//    req := client.ModifyPropertyRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/euprop-2010-01-01/ModifyProperty
func (c *Client) ModifyPropertyRequest(input *ModifyPropertyInput) ModifyPropertyRequest {
	op := &aws.Operation{
		Name:       opModifyProperty,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ModifyPropertyInput{}
	}

	req := c.newRequest(op, input, &ModifyPropertyOutput{})
	return ModifyPropertyRequest{Request: req, Input: input, Copy: c.ModifyPropertyRequest}
}

// ModifyPropertyRequest is the request type for the
// ModifyProperty API operation.
type ModifyPropertyRequest struct {
	*aws.Request
	Input *ModifyPropertyInput
	Copy  func(*ModifyPropertyInput) ModifyPropertyRequest
}

// Send marshals and sends the ModifyProperty API request.
func (r ModifyPropertyRequest) Send(ctx context.Context) (*ModifyPropertyResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &ModifyPropertyResponse{
		ModifyPropertyOutput: r.Request.Data.(*ModifyPropertyOutput),
		response:             &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// ModifyPropertyResponse is the response type for the
// ModifyProperty API operation.
type ModifyPropertyResponse struct {
	*ModifyPropertyOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// ModifyProperty request.
func (r *ModifyPropertyResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
