// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package euprop

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sjones4/eucalyptus-sdk-go/internal/awsutil"
)

type DescribePropertiesInput struct {
	_ struct{} `type:"structure"`

	Properties []string `locationName:"Property" type:"list"`
}

// String returns the string representation
func (s DescribePropertiesInput) String() string {
	return awsutil.Prettify(s)
}

type DescribePropertiesOutput struct {
	_ struct{} `locationName:"DescribePropertiesResponseType" type:"structure"`

	Properties []Property `locationName:"properties" locationNameList:"item" type:"list"`
}

// String returns the string representation
func (s DescribePropertiesOutput) String() string {
	return awsutil.Prettify(s)
}

const opDescribeProperties = "DescribeProperties"

// DescribePropertiesRequest returns a request value for making API operation for
// Eucalyptus Cloud Properties Service.
//
//    // Example sending a request using DescribePropertiesRequest.
//    req := client.DescribePropertiesRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/euprop-2010-01-01/DescribeProperties
func (c *Client) DescribePropertiesRequest(input *DescribePropertiesInput) DescribePropertiesRequest {
	op := &aws.Operation{
		Name:       opDescribeProperties,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DescribePropertiesInput{}
	}

	req := c.newRequest(op, input, &DescribePropertiesOutput{})
	return DescribePropertiesRequest{Request: req, Input: input, Copy: c.DescribePropertiesRequest}
}

// DescribePropertiesRequest is the request type for the
// DescribeProperties API operation.
type DescribePropertiesRequest struct {
	*aws.Request
	Input *DescribePropertiesInput
	Copy  func(*DescribePropertiesInput) DescribePropertiesRequest
}

// Send marshals and sends the DescribeProperties API request.
func (r DescribePropertiesRequest) Send(ctx context.Context) (*DescribePropertiesResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DescribePropertiesResponse{
		DescribePropertiesOutput: r.Request.Data.(*DescribePropertiesOutput),
		response:                 &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DescribePropertiesResponse is the response type for the
// DescribeProperties API operation.
type DescribePropertiesResponse struct {
	*DescribePropertiesOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DescribeProperties request.
func (r *DescribePropertiesResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
