// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package euprop

const (

	// ErrCodeModifyPropertyException for service response error code
	// "ModifyPropertyValueType".
	ErrCodeModifyPropertyException = "ModifyPropertyValueType"

	// ErrCodeServiceFailureException for service response error code
	// "ServiceFailure".
	ErrCodeServiceFailureException = "ServiceFailure"
)
