// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package euprop

import (
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sjones4/eucalyptus-sdk-go/internal/awsutil"
)

var _ aws.Config
var _ = awsutil.Prettify

type Property struct {
	_ struct{} `type:"structure"`

	Name *string `locationName:"name" type:"string"`

	Value *string `locationName:"value" type:"string"`
}

// String returns the string representation
func (s Property) String() string {
	return awsutil.Prettify(s)
}
