// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package euprop

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/sjones4/eucalyptus-sdk-go/internal/awsutil"
)

type ModifyPropertyValueInput struct {
	_ struct{} `type:"structure"`

	// Name is a required field
	Name *string `locationName:"Name" type:"string" required:"true"`

	Reset *bool `locationName:"Reset" type:"boolean"`

	Value *string `locationName:"Value" type:"string"`
}

// String returns the string representation
func (s ModifyPropertyValueInput) String() string {
	return awsutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *ModifyPropertyValueInput) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "ModifyPropertyValueInput"}

	if s.Name == nil {
		invalidParams.Add(aws.NewErrParamRequired("Name"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}

type ModifyPropertyValueOutput struct {
	_ struct{} `locationName:"ModifyPropertyValueResponseType" type:"structure"`

	Name *string `locationName:"name" type:"string"`

	OldValue *string `locationName:"oldValue" type:"string"`

	Value *string `locationName:"value" type:"string"`
}

// String returns the string representation
func (s ModifyPropertyValueOutput) String() string {
	return awsutil.Prettify(s)
}

const opModifyPropertyValue = "ModifyPropertyValue"

// ModifyPropertyValueRequest returns a request value for making API operation for
// Eucalyptus Cloud Properties Service.
//
//    // Example sending a request using ModifyPropertyValueRequest.
//    req := client.ModifyPropertyValueRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/euprop-2010-01-01/ModifyPropertyValue
func (c *Client) ModifyPropertyValueRequest(input *ModifyPropertyValueInput) ModifyPropertyValueRequest {
	op := &aws.Operation{
		Name:       opModifyPropertyValue,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ModifyPropertyValueInput{}
	}

	req := c.newRequest(op, input, &ModifyPropertyValueOutput{})
	return ModifyPropertyValueRequest{Request: req, Input: input, Copy: c.ModifyPropertyValueRequest}
}

// ModifyPropertyValueRequest is the request type for the
// ModifyPropertyValue API operation.
type ModifyPropertyValueRequest struct {
	*aws.Request
	Input *ModifyPropertyValueInput
	Copy  func(*ModifyPropertyValueInput) ModifyPropertyValueRequest
}

// Send marshals and sends the ModifyPropertyValue API request.
func (r ModifyPropertyValueRequest) Send(ctx context.Context) (*ModifyPropertyValueResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &ModifyPropertyValueResponse{
		ModifyPropertyValueOutput: r.Request.Data.(*ModifyPropertyValueOutput),
		response:                  &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// ModifyPropertyValueResponse is the response type for the
// ModifyPropertyValue API operation.
type ModifyPropertyValueResponse struct {
	*ModifyPropertyValueOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// ModifyPropertyValue request.
func (r *ModifyPropertyValueResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
