// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package euserviface provides an interface to enable mocking the Eucalyptus Cloud Service Management Service service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package euserviface

import (
	"github.com/aws/aws-sdk-go-v2/service/euserv"
)

// ClientAPI provides an interface to enable mocking the
// euserv.Client methods. This make unit testing your code that
// calls out to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // Eucalyptus Services.
//    func myFunc(svc euserviface.ClientAPI) bool {
//        // Make svc.DeregisterService request
//    }
//
//    func main() {
//        cfg, err := external.LoadDefaultAWSConfig()
//        if err != nil {
//            panic("failed to load config, " + err.Error())
//        }
//
//        svc := euserv.New(cfg)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockClientClient struct {
//        euserviface.ClientPI
//    }
//    func (m *mockClientClient) DeregisterService(input *euserv.DeregisterServiceInput) (*euserv.DeregisterServiceOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockClientClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type ClientAPI interface {
	DeregisterServiceRequest(*euserv.DeregisterServiceInput) euserv.DeregisterServiceRequest

	DescribeAvailableServiceTypesRequest(*euserv.DescribeAvailableServiceTypesInput) euserv.DescribeAvailableServiceTypesRequest

	DescribeServiceCertificatesRequest(*euserv.DescribeServiceCertificatesInput) euserv.DescribeServiceCertificatesRequest

	DescribeServicesRequest(*euserv.DescribeServicesInput) euserv.DescribeServicesRequest

	ModifyServiceRequest(*euserv.ModifyServiceInput) euserv.ModifyServiceRequest

	RegisterServiceRequest(*euserv.RegisterServiceInput) euserv.RegisterServiceRequest
}

var _ ClientAPI = (*euserv.Client)(nil)
